export const openApiInfoDescription = [
  "Normal's public REST API for one User's server-side personal automations.",
  "",
  "## Getting started",
  "",
  "Create an API Key from the signed-in dashboard at `/dashboard/api-keys`. Choose a unique name, any non-empty subset of the four permissions, the WhatsApp Connections this automation may use, and an optional expiry. The plaintext credential is shown once. If that response is lost, create a replacement key.",
  "",
  "Call `https://api.normal.fast` from a server. Do not put an API Key in a browser, mobile app, query parameter, cookie, or this documentation site.",
  "",
  "```bash",
  "curl -sS https://api.normal.fast/v1/connections \\",
  "  -H 'Authorization: Bearer <API Key>'",
  "```",
  "",
  "Signed-in API Key management routes (`/v1/api-keys`) are product routes. They require a Clerk bearer token, the exact web Origin, and — for creation — first-factor verification within five minutes. They are not authenticated with an API Key.",
  "",
  "## Server-side authentication",
  "",
  "Send one `Authorization: Bearer <API Key>` header. The credential uses the `normal_apk_` split format: a public `apk_` handle and a high-entropy secret shown only at creation. Duplicate or oversized authorization headers are rejected.",
  "",
  "Neon is the sole authority for validity, selected Connections, permissions, expiry, and revocation. There is no cache that can extend a revoked or expired key. Invalid, malformed, expired, or revoked credentials return the same 401 Problem Details shape.",
  "",
  "## Permissions",
  "",
  "| Permission | Capabilities |",
  "| --- | --- |",
  "| `connections:read` | List WhatsApp Connections explicitly selected for this API Key. |",
  "| `directory:read` | Page Directory contacts and currently joined groups. |",
  "| `messages:read` | Page WhatsApp Conversations, complete Stored Messages, private exact-word search, and eligible Stored Media. |",
  "| `messages:send` | Create or replay text, PDF, or image Send Operations and read Send Status for operations created by this key. |",
  "",
  "Permissions are independent. `messages:send` never implies Directory or Stored Message read permission. A newly created WhatsApp Connection is never added to an existing API Key.",
  "",
  "## Pagination",
  "",
  "Collection responses use `data`, `pagination`, and optional `meta`. `pagination` contains `next_cursor` and `has_more`. The default page size is 20 and the maximum is 50, except Stored Message search which remains capped at 20.",
  "",
  "REST cursors are short-lived HMAC keyset cursors bound to the calling API Key, operation, WhatsApp Connection, normalized filters or a keyed digest of search terms, limit, sort version, and a 15-minute expiry. MCP cursors are not accepted. A tampered, expired, or rebound cursor returns 400. Search terms themselves never appear in a cursor.",
  "",
  "## Problem Details",
  "",
  "REST errors use RFC 9457 `application/problem+json` with `type`, `title`, `status`, a safe `detail`, a stable Normal `code`, and optional `retryable`, `retry_after_seconds`, or `resets_at`.",
  "",
  "| Code | Status | Meaning |",
  "| --- | --- | --- |",
  "| `invalid_credentials` | 401 | Missing, malformed, expired, or revoked API Key. |",
  "| `insufficient_permission` | 403 | The grant does not include the required permission. |",
  "| `not_found` | 404 | Unknown, cross-tenant, deleted, excluded, or mismatched resource. The shape is constant. |",
  "| `invalid_request` / `invalid_cursor` | 400 | Closed request, header, or cursor contract failed. |",
  "| `idempotency_conflict` / `connection_unavailable` | 409 | Idempotency payload mismatch, or the Connection is not connected for a new send. |",
  "| `rate_limited` | 429 | Personal Account or API Key quota is exhausted. |",
  "| `unavailable` | 503 | Authentication, audit, or quota authority is unavailable. The request fails closed. |",
  "",
  "Each `type` is `https://docs.normal.fast/problems/{code}`.",
  "",
  "## Idempotency",
  "",
  "`POST /v1/connections/{connection_id}/send-operations` requires `Idempotency-Key` using the NanoID default alphabet (21 characters). Exact replay returns the existing Send Operation without calling the provider again or consuming send quota. A changed payload under the same key returns `idempotency_conflict`.",
  "",
  "## PDF and image sends",
  "",
  "A Send Operation accepts exact `text`; a PDF with `file_name` and exactly one of `pdf_url` or standard padded `pdf_base64`; or a JPEG/PNG image with exactly one of `image_url` or standard padded `image_base64` and an optional `caption`. Image requests do not accept a filename. Each request accepts exactly one destination: `recipient_id`, E.164 `phone`, or WhatsApp `username`.",
  "",
  "```bash",
  "curl --request POST \\",
  "  'https://api.normal.fast/v1/connections/<CONNECTION_ID>/send-operations' \\",
  "  --header 'Authorization: Bearer <API Key>' \\",
  "  --header 'Content-Type: application/json' \\",
  "  --header 'Idempotency-Key: <21-character key>' \\",
  '  --data \'{"phone":"<E.164_PHONE>","file_name":"report.pdf","pdf_url":"https://files.example.com/report.pdf"}\'',
  "```",
  "",
  "PDFs must be 8 through 16,777,216 bytes and begin with a PDF version signature. `file_name` must be 5-255 characters, contain no path separators or control characters, and end in `.pdf` case-insensitively. URL sources must use HTTPS without credentials or a custom port. Normal validates every redirect and rejects private or reserved network targets.",
  "",
  "The exact PDF bytes and filename, not the source URL, are bound to idempotency. The verified PDF is encrypted as a Pending Send File, counts against the Personal Account's Stored Media quota, and expires at the earliest of seven days, the Message Retention Policy deadline, Connection Deletion, or Personal Account Deletion. Normal never retains the source URL or the provider upload URL.",
  "",
  "Images must be JPEG or PNG and no larger than 5,000,000 bytes. An optional `caption` is validated exactly like `text`: 1-4,096 Unicode scalar values, not solely Unicode whitespace, with no unpaired surrogate. Image URL sources follow the same HTTPS, credentials, port, redirect, and public-network rules as PDF URLs.",
  "",
  "## Ambiguous sends",
  "",
  "A Send Operation is not a Stored Message. After the durable provider-attempt boundary, `failed` and `unknown` remain Send Operation resources, not HTTP execution errors. An unknown outcome means the provider may have accepted the message. Normal never automatically retries an unknown Send Operation. `GET /v1/connections/{connection_id}/send-operations/{send_operation_id}` returns the originating key's current local Send Status and never contacts the provider.",
  "",
  "## Retention and history coverage",
  "",
  "Stored Messages, Stored Media, Pending Send Content, and Pending Send Files follow the User's Message Retention Policy. The default is 30 days. Pending Send Content and Pending Send Files also expire at most seven days after Send Operation creation.",
  "",
  "Message pages include the Message History Window (`history_starts_at`, `history_start_reason`) and intersecting Ingestion Gaps. History is observed, not provider-certified complete. The absence of a known gap does not prove that every provider message arrived.",
  "",
  "Disconnected WhatsApp Connections remain readable for retained history. New Send Operations require a connected Connection.",
  "",
  "## Media",
  "",
  "Eligible Stored Media appears as an authenticated nested path on the Stored Message, never an MCP URI, public URL, provider URL, R2 URL, or presigned URL. `GET` that path with the same API Key. v1 returns the complete ready object up to 16 MiB after Activity Log admission and full-byte quota reservation. Responses use the normalized MIME type, a sanitized optional filename, and `Cache-Control: private, no-store`. Range and chunk downloads are not provided.",
  "",
  "Unknown, mismatched, excluded, non-ready, unauthorized, or oversized media share one constant-shape 404.",
  "",
  "## Deletion",
  "",
  "Connection Deletion immediately removes that WhatsApp Connection from every API Key. If it was a key's last selected Connection, the key is revoked and its digest is cleared. Personal Account Deletion revokes every API Key and clears every digest before purge continues. Safe expired or revoked metadata remains visible in the dashboard for 90 days, then purges. Activity Logs retain their own 90-day window.",
  "",
  "WhatsApp Recipient Exclusions apply beneath every API Key. Excluded recipients are absent from Directory, conversation, message, and media results. A send to an excluded recipient returns the same 404 as an unknown recipient. Because a Direct Address cannot be proven distinct from an excluded recipient, all direct phone and username sends fail with that same 404 while any exclusion is active on the Connection. Removing an exclusion never restores purged history or Pending Send Content.",
  "",
  "## Restore invalidation",
  "",
  "A production database restore globally invalidates every restored API Key before verification traffic reopens. Digests are cleared and the API Key HMAC authority is rotated. Previous HMAC generations are not accepted as a fallback. Users create replacement keys after recovery.",
  "",
  "## Privacy",
  "",
  "Direct phone numbers and usernames are accepted only in the closed Send Operation request body. They are used in memory for one provider attempt and never persisted, returned, logged, or placed in telemetry. Other public fields use opaque handles (`con_`, `ctc_`, `grp_`, `cvs_`, `msg_`, `med_`, `snd_`, `apk_`) and suffix-only phone presentation.",
  "",
  "Search terms, message content, media bytes, credentials, credential digests, full phone numbers, provider payloads, raw bodies, and tenant identifiers must not appear in URLs, cursors, Activity Logs, telemetry, or Problem Details. `POST /v1/connections/{connection_id}/messages/search` accepts terms only in a closed JSON body and binds pagination to a keyed digest of the normalized terms.",
  "",
  "This documentation site cannot execute authenticated requests or persist an API Key. Server-side curl and language examples are generated for copy-out use only.",
].join("\n");
